services:
  - type: web
    name: job-ranking-api
    env: python
    # Optimization: Clear old caches before installing
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
